[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "osaka"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read-write", path = "./" }]

[fuzz]
runs = 512

[invariant]
runs = 64
depth = 32
fail_on_revert = false

[rpc_endpoints]
arc = "https://rpc.mainnet.arc.io"
